---
kind: pipeline
type: ssh
name: CI
server:
  host: 111.186.59.59
  user: drone
  ssh_key:
    from_secret: joj3-test

steps:
- name: build
  commands:
  - go env -w GOPROXY=https://goproxy.cn,direct
  - export PATH=$PATH:/usr/local/go/bin
  - make
  - ./_example/simple/run.sh
  - cp build/joj3 ~/.local/bin/joj3
