---
kind: pipeline
type: ssh
name: CI
server:
    host: 111.186.59.59
    user: drone
    ssh_key:
        from_secret: joj3-test

steps:
    - name: prepare
      commands:
          - go env -w GOPROXY=https://goproxy.cn,direct
          - whoami
          - pwd
          - env
          - go version
          - go env
    - name: build
      commands:
          - make
    - name: test
      environment:
          CONF_GITEATOKEN:
              from_secret: gitea-token
      commands:
          - make test
    - name: store
      commands:
          - cp build/joj3 /home/drone/.local/bin/joj3
