version: "2"
linters:
  enable:
    - bidichk
    - dupl
    - gocritic
    - gosec
    - nakedret
    - nolintlint
    - prealloc
    - staticcheck
    - testifylint
    - unconvert
    - unparam
    - usetesting
    - wastedassign
  settings:
    staticcheck:
      checks:
        - all
        - -ST1005
  exclusions:
    generated: lax
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    paths:
      - third_party$
      - builtin$
      - examples$
formatters:
  enable:
    - gofmt
    - gofumpt
    - goimports
  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin$
      - examples$
