linters:
  enable:
    - bidichk
    - dupl
    - errcheck
    - gocritic
    - gofmt
    - gofumpt
    - goimports
    - gosec
    - gosimple
    - govet
    - ineffassign
    - nakedret
    - nolintlint
    - prealloc
    - staticcheck
    - stylecheck
    - testifylint
    - typecheck
    - unconvert
    - unused
    - unparam
    - usetesting
    - wastedassign
linters-settings:
  stylecheck:
    checks: ["all", "-ST1005"]
