---
repos:
    - repo: https://github.com/pre-commit/pre-commit-hooks
      rev: v4.6.0
      hooks:
          - id: check-yaml
          - id: end-of-file-fixer
          - id: trailing-whitespace
    - repo: https://github.com/mrtazz/checkmake.git
      rev: 0.2.2
      hooks:
          - id: checkmake
    - repo: https://github.com/jumanjihouse/pre-commit-hook-yamlfmt
      rev: 0.2.3
      hooks:
          - id: yamlfmt
    - repo: https://github.com/Bahjat/pre-commit-golang
      rev: v1.0.3
      hooks:
          - id: gofumpt
    - repo: https://github.com/dnephin/pre-commit-golang
      rev: v0.5.1
      hooks:
          - id: go-fmt
          - id: go-imports
          - id: golangci-lint
          - id: go-mod-tidy
    - repo: local
      hooks:
          - id: make-build
            name: make build
            entry: make build
            language: system
          - id: make-test
            name: make test
            entry: make test
            language: system
